services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: springforum
      POSTGRES_USER: uipko
      POSTGRES_PASSWORD: uipko
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: